[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "arista-eos-bgp-basic"
version = "0.1.0"
description = "Python project for basic Arista EOS BGP configuration"
requires-python = ">=3.8"
dependencies = [
    "netmiko>=4.3.0,<5.0.0",
    "PyYAML>=6.0,<7.0",
    "python-dateutil>=2.8.2,<3.0.0",
    "pydantic>=2.0.0,<3.0.0",
    "colorlog>=6.7.0,<7.0.0",
    "tenacity>=8.2.3,<9.0.0",
]

[tool.setuptools]
packages = []