---
name: arista-eos-config-backup

mgmt:
  network: agw-mgmt
  ipv4-subnet: 1.1.1.0/24

topology:
  nodes:
    agw:
      kind: linux
      image: ghcr.io/torerodev/torero-container:${TORERO_VERSION:=latest}
      labels:
        graph-icon: controller
      mgmt-ipv4: 1.1.1.5
      env:
        ENABLE_SSH_ADMIN: "true"
      binds:
        - $PWD/data:/home/admin/data
      exec:
        - "runuser -u admin -- torero db import --repository https://github.com/torerodev/showtime.git imports/ansible/arista-eos-config-backup.yml"
    
    eos-sw-00:
      kind: arista_ceos
      image: ceos:${CEOS_VERSION:=4.33.2F}
      startup-config: ./config/base.cfg
      mgmt-ipv4: 1.1.1.6

  links:
    - endpoints: [ "eos-sw-00:eth1", "agw:eth1" ]
...