---
- name: Ensure required tenant parameters are provided
  ansible.builtin.assert:
    that:
      - netbox_tenant.name is defined
    fail_msg: "Missing required tenant parameters"

- name: Add tenant to NetBox
  netbox.netbox.netbox_tenant:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ netbox_validate_certs | default(false) }}"
    data:
      name: "{{ netbox_tenant.name }}"
      slug: "{{ netbox_tenant.slug | default(netbox_tenant.name | lower | replace(' ', '-')) }}"
      description: "{{ netbox_tenant.description | default(omit) }}"
      comments: "{{ netbox_tenant.comments | default(omit) }}"
      tags: "{{ netbox_tenant.tags | default(omit) }}"
    state: present
  register: netbox_tenant_result

- name: Show tenant result
  ansible.builtin.debug:
    var: netbox_tenant_result
