---
- name: Ensure required interface parameters are provided
  ansible.builtin.assert:
    that:
      - netbox_interface.device is defined
      - netbox_interface.name is defined
    fail_msg: "Missing required interface parameters"

- name: Add interface to NetBox
  netbox.netbox.netbox_device_interface:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ netbox_validate_certs | default(false) }}"
    data:
      device: "{{ netbox_interface.device }}"
      name: "{{ netbox_interface.name }}"
      
      type: "{{ netbox_interface.type | default('1000base-t') }}"
      enabled: "{{ netbox_interface.enabled | default(true) }}"
      mtu: "{{ netbox_interface.mtu | default(omit) }}"
      mac_address: "{{ netbox_interface.mac_address | default(omit) }}"
      mgmt_only: "{{ netbox_interface.mgmt_only | default(false) }}"
      description: "{{ netbox_interface.description | default(omit) }}"
      
      mode: "{{ netbox_interface.mode | default(omit) }}"
      untagged_vlan: "{{ netbox_interface.untagged_vlan | default(omit) }}"
      tagged_vlans: "{{ netbox_interface.tagged_vlans | default(omit) }}"
      
      lag: "{{ netbox_interface.lag | default(omit) }}"
      
      custom_fields: "{{ netbox_interface.custom_fields | default(omit) }}"
      tags: "{{ netbox_interface.tags | default(omit) }}"
    state: present
  register: netbox_interface_result

- name: Show interface result
  ansible.builtin.debug:
    var: netbox_interface_result
