---
- name: Ensure required aggregate parameters are provided
  ansible.builtin.assert:
    that:
      - netbox_aggregate.prefix is defined
      - netbox_aggregate.rir is defined
    fail_msg: "Missing required aggregate parameters"

- name: Add aggregate to NetBox
  netbox.netbox.netbox_aggregate:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ netbox_validate_certs | default(false) }}"
    data:
      prefix: "{{ netbox_aggregate.prefix }}"
      rir: "{{ netbox_aggregate.rir }}"
      tenant: "{{ netbox_aggregate.tenant | default(omit) }}"
      date_added: "{{ netbox_aggregate.date_added | default(omit) }}"
      description: "{{ netbox_aggregate.description | default(omit) }}"
      tags: "{{ netbox_aggregate.tags | default(omit) }}"
    state: present
  register: netbox_aggregate_result

- name: Show aggregate result
  ansible.builtin.debug:
    var: netbox_aggregate_result
