---
- name: Ensure required device parameters are provided
  ansible.builtin.assert:
    that:
      - netbox_device.name is defined
      - netbox_device.device_type is defined
      - netbox_device.site is defined
    fail_msg: "Missing required device parameters"

- name: Add device to NetBox
  netbox.netbox.netbox_device:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ netbox_validate_certs | default(false) }}"
    data:
      name: "{{ netbox_device.name }}"
      device_type: "{{ netbox_device.device_type }}"
      site: "{{ netbox_device.site }}"
      
      status: "{{ netbox_device.status | default('active') }}"
      device_role: "{{ netbox_device.role | default(omit) }}"
      tenant: "{{ netbox_device.tenant | default(omit) }}"
      platform: "{{ netbox_device.platform | default(omit) }}"
      serial: "{{ netbox_device.serial | default(omit) }}"
      asset_tag: "{{ netbox_device.asset_tag | default(omit) }}"
      
      rack: "{{ netbox_device.rack | default(omit) }}"
      position: "{{ netbox_device.position | default(omit) }}"
      face: "{{ netbox_device.face | default(omit) }}"
      location: "{{ netbox_device.location | default(omit) }}"
      
      primary_ip4: "{{ netbox_device.primary_ip4 | default(omit) }}"
      primary_ip6: "{{ netbox_device.primary_ip6 | default(omit) }}"
      cluster: "{{ netbox_device.cluster | default(omit) }}"
      virtual_chassis: "{{ netbox_device.virtual_chassis | default(omit) }}"
      vc_position: "{{ netbox_device.vc_position | default(omit) }}"
      vc_priority: "{{ netbox_device.vc_priority | default(omit) }}"
      
      description: "{{ netbox_device.description | default(omit) }}"
      comments: "{{ netbox_device.comments | default(omit) }}"
      local_context_data: "{{ netbox_device.local_context_data | default(omit) }}"
      
      custom_fields: "{{ netbox_device.custom_fields | default(omit) }}"
      tags: "{{ netbox_device.tags | default(omit) }}"
    state: present
  register: netbox_device_result

- name: Show device result
  ansible.builtin.debug:
    var: netbox_device_result
