---
- name: Ensure required aggregate parameters are provided
  ansible.builtin.assert:
    that:
      - netbox_aggregate.prefix is defined
      - netbox_aggregate.rir is defined
    fail_msg: "Missing required aggregate parameters"

- name: Remove aggregate from NetBox
  netbox.netbox.netbox_aggregate:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ netbox_validate_certs | default(false) }}"
    data:
      prefix: "{{ netbox_aggregate.prefix }}"
      rir: "{{ netbox_aggregate.rir }}"
    state: absent
  register: netbox_aggregate_result

- name: Show aggregate removal result
  ansible.builtin.debug:
    var: netbox_aggregate_result
