---
- name: Ensure required ASN parameters are provided
  ansible.builtin.assert:
    that:
      - netbox_asn.asn is defined
    fail_msg: "Missing required ASN parameters"

- name: Remove ASN from NetBox
  netbox.netbox.netbox_asn:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ netbox_validate_certs | default(false) }}"
    data:
      asn: "{{ netbox_asn.asn }}"
    state: absent
  register: netbox_asn_result

- name: Show ASN removal result
  ansible.builtin.debug:
    var: netbox_asn_result
