---
- name: Ensure required device type parameters are provided
  ansible.builtin.assert:
    that:
      - netbox_device_type.model is defined
      - netbox_device_type.manufacturer is defined
    fail_msg: "Missing required device type parameters"

- name: Remove device type from NetBox
  netbox.netbox.netbox_device_type:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ netbox_validate_certs | default(false) }}"
    data:
      model: "{{ netbox_device_type.model }}"
      manufacturer: "{{ netbox_device_type.manufacturer }}"
    state: absent
  register: netbox_device_type_result

- name: Show device type removal result
  ansible.builtin.debug:
    var: netbox_device_type_result
