---
- name: Ensure required VLAN parameters are provided
  ansible.builtin.assert:
    that:
      - netbox_vlan.vid is defined
      - netbox_vlan.name is defined
    fail_msg: "Missing required VLAN parameters"

- name: Remove VLAN from NetBox
  netbox.netbox.netbox_vlan:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ netbox_validate_certs | default(false) }}"
    data:
      vid: "{{ netbox_vlan.vid }}"
      name: "{{ netbox_vlan.name }}"
      site: "{{ netbox_vlan.site | default(omit) }}"
    state: absent
  register: netbox_vlan_result

- name: Show VLAN removal result
  ansible.builtin.debug:
    var: netbox_vlan_result
