---
- name: Ensure required site parameters are provided
  ansible.builtin.assert:
    that:
      - netbox_site.name is defined
    fail_msg: "Missing required site parameters"

- name: Remove site from NetBox
  netbox.netbox.netbox_site:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ netbox_validate_certs | default(false) }}"
    data:
      name: "{{ netbox_site.name }}"
    state: absent
  register: netbox_site_result

- name: Show site removal result
  ansible.builtin.debug:
    var: netbox_site_result
