---
- name: Ensure required interface parameters are provided
  ansible.builtin.assert:
    that:
      - netbox_interface.device is defined
      - netbox_interface.name is defined
    fail_msg: "Missing required interface parameters"

- name: Remove interface from NetBox
  netbox.netbox.netbox_device_interface:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ netbox_validate_certs | default(false) }}"
    data:
      device: "{{ netbox_interface.device }}"
      name: "{{ netbox_interface.name }}"
    state: absent
  register: netbox_interface_result

- name: Show interface removal result
  ansible.builtin.debug:
    var: netbox_interface_result
