---
- name: Ensure required VRF parameters are provided
  ansible.builtin.assert:
    that:
      - netbox_vrf.name is defined
    fail_msg: "Missing required VRF parameters"

- name: Remove VRF from NetBox
  netbox.netbox.netbox_vrf:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ netbox_validate_certs | default(false) }}"
    data:
      name: "{{ netbox_vrf.name }}"
    state: absent
  register: netbox_vrf_result

- name: Show VRF removal result
  ansible.builtin.debug:
    var: netbox_vrf_result
