---
repositories:
    - name: showtime
      description: Show off your automations!
      url: https://github.com/torerodev/showtime.git
      reference: main
      tags:
        - demo
        - lab
        - torero

services:
    - name: arista-eos-config-backup
      type: ansible-playbook
      description: Ansible playbook to backup Arista configurations
      working-directory: library/ansible
      playbooks:
        - playbooks/arista/backup-eos-config.yml
      repository: showtime
      runtime:
        inventory:
          - inventory/ansible_eos_config_backup.yml
      tags:
        - arista-eos-config-backup
...