---
- name: Add resources to NetBox
  hosts: localhost
  gather_facts: false
  vars_files:
    - "../../inventory/group_vars/netbox_settings.yml"
  vars:
    resource_file_path: "{{ playbook_dir }}/../../resources/{{ resource_file | default('lab_network.yml') }}"
  
  pre_tasks:
    - name: Check if NetBox token is set
      ansible.builtin.fail:
        msg: "NetBox API token not set. Please set the NETBOX_TOKEN environment variable."
      when: not lookup('env', 'NETBOX_TOKEN')

    - name: Show NetBox connection info
      ansible.builtin.debug:
        msg: 
          - "NetBox URL: {{ netbox_url }}"
          - "NetBox token is set: {{ lookup('env', 'NETBOX_TOKEN') | length > 0 }}"
    
    - name: Check if resource file exists
      ansible.builtin.stat:
        path: "{{ resource_file_path }}"
      register: resource_file_stat
      
    - name: Fail if resource file doesn't exist
      ansible.builtin.fail:
        msg: "Resource file not found at {{ resource_file_path }}"
      when: not resource_file_stat.stat.exists
      
    - name: Show resource file path
      ansible.builtin.debug:
        msg: "Using resource file at: {{ resource_file_path }}"
        
    - name: Include resource file
      ansible.builtin.include_vars:
        file: "{{ resource_file_path }}"
  
  tasks:
    # Tags should be created first as they may be used by other resources
    - name: Add tags
      include_tasks: tasks/add_tag.yml
      vars:
        netbox_tag: "{{ item }}"
      loop: "{{ netbox_tags | default([]) }}"
      when: netbox_tags is defined
    
    # Organization resources
    - name: Add regions
      include_tasks: tasks/add_region.yml
      vars:
        netbox_region: "{{ item }}"
      loop: "{{ netbox_regions | default([]) }}"
      when: netbox_regions is defined
      
    - name: Add tenants
      include_tasks: tasks/add_tenant.yml
      vars:
        netbox_tenant: "{{ item }}"
      loop: "{{ netbox_tenants | default([]) }}"
      when: netbox_tenants is defined
      
    - name: Add sites
      include_tasks: tasks/add_site.yml
      vars:
        netbox_site: "{{ item }}"
      loop: "{{ netbox_sites | default([]) }}"
      when: netbox_sites is defined
      
    # IPAM resources
    - name: Add IPAM roles
      include_tasks: tasks/add_ipam_role.yml
      vars:
        netbox_ipam_role: "{{ item }}"
      loop: "{{ netbox_ipam_roles | default([]) }}"
      when: netbox_ipam_roles is defined
      
    - name: Add RIRs
      include_tasks: tasks/add_rir.yml
      vars:
        netbox_rir: "{{ item }}"
      loop: "{{ netbox_rirs | default([]) }}"
      when: netbox_rirs is defined
      
    - name: Add ASNs
      include_tasks: tasks/add_asn.yml
      vars:
        netbox_asn: "{{ item }}"
      loop: "{{ netbox_asns | default([]) }}"
      when: netbox_asns is defined
    - name: Add BGP ASNs
      include_tasks: tasks/add_bgp_asn.yml
      vars:
        netbox_bgp_asn: "{{ item }}"
      loop: "{{ netbox_bgp_asns | default([]) }}"
      when: netbox_bgp_asns is defined
      
    - name: Add route targets
      include_tasks: tasks/add_route_target.yml
      vars:
        netbox_route_target: "{{ item }}"
      loop: "{{ netbox_route_targets | default([]) }}"
      when: netbox_route_targets is defined
      
    - name: Add VRFs
      include_tasks: tasks/add_vrf.yml
      vars:
        netbox_vrf: "{{ item }}"
      loop: "{{ netbox_vrfs | default([]) }}"
      when: netbox_vrfs is defined
      
    - name: Add VLANs
      include_tasks: tasks/add_vlan.yml
      vars:
        netbox_vlan: "{{ item }}"
      loop: "{{ netbox_vlans | default([]) }}"
      when: netbox_vlans is defined
      
    - name: Add aggregates
      include_tasks: tasks/add_aggregate.yml
      vars:
        netbox_aggregate: "{{ item }}"
      loop: "{{ netbox_aggregates | default([]) }}"
      when: netbox_aggregates is defined
      
    - name: Add prefixes
      include_tasks: tasks/add_prefix.yml
      vars:
        netbox_prefix: "{{ item }}"
      loop: "{{ netbox_prefixes | default([]) }}"
      when: netbox_prefixes is defined
      
    - name: Add IP addresses
      include_tasks: tasks/add_ip_address.yml
      vars:
        netbox_ip_address: "{{ item }}"
      loop: "{{ netbox_ip_addresses | default([]) }}"
      when: netbox_ip_addresses is defined
      
    # Manufacturer and device components  
    - name: Add manufacturers
      include_tasks: tasks/add_manufacturer.yml
      vars:
        netbox_manufacturer: "{{ item }}"
      loop: "{{ netbox_manufacturers | default([]) }}"
      when: netbox_manufacturers is defined
    - name: Add device types
      include_tasks: tasks/add_device_type.yml
      vars:
        netbox_device_type: "{{ item }}"
      loop: "{{ netbox_device_types | default([]) }}"
      when: netbox_device_types is defined
      
    - name: Add device roles
      include_tasks: tasks/add_device_role.yml
      vars:
        netbox_device_role: "{{ item }}"
      loop: "{{ netbox_device_roles | default([]) }}"
      when: netbox_device_roles is defined
      
    - name: Add platforms
      include_tasks: tasks/add_platform.yml
      vars:
        netbox_platform: "{{ item }}"
      loop: "{{ netbox_platforms | default([]) }}"
      when: netbox_platforms is defined
      
    - name: Add devices
      include_tasks: tasks/add_device.yml
      vars:
        netbox_device: "{{ item }}"
      loop: "{{ netbox_devices | default([]) }}"
      when: netbox_devices is defined
      
    - name: Add interfaces
      include_tasks: tasks/add_interface.yml
      vars:
        netbox_interface: "{{ item }}"
      loop: "{{ netbox_interfaces | default([]) }}"
      when: netbox_interfaces is defined
...