[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ansible-arista-eos-config-backup"
version = "0.1.0"
description = "Ansible project for Arista EOS configuration backup"
requires-python = ">=3.8"
dependencies = [
    "paramiko>=2.11.0",
    "netmiko>=4.1.0",
    "requests>=2.28.1",
    "PyYAML>=6.0",
    "jinja2>=3.1.2",
    "ncclient>=0.6.13",
    "jsonschema>=4.17.3",
    "pyeapi>=0.8.4",
]

[tool.setuptools]
packages = []