---
all:
  children:
    eos_single_node:
      vars:
        ansible_user: admin
        ansible_password: admin
        ansible_become: true
        ansible_become_method: enable
        ansible_become_password: admin
        ansible_connection: network_cli
        ansible_network_os: arista.eos.eos
        config_backups: "~/backups/arista"
      hosts:
        eos-sw-00:
          ansible_host: 1.1.1.6
...