---
all:
  vars:
    ansible_user: admin
    ansible_password: admin
    ansible_become: true
    ansible_become_method: enable
    ansible_become_password: admin
    ansible_connection: network_cli
    ansible_network_os: arista.eos.eos
    config_backups: "~/backups/arista"

  children:
    arista:
      hosts:
        spine1:
          ansible_host: 172.20.20.11
        spine2:
          ansible_host: 172.20.20.12
        leaf1:
          ansible_host: 172.20.20.21
        leaf2:
          ansible_host: 172.20.20.22
        leaf3:
          ansible_host: 172.20.20.23
        leaf4:
          ansible_host: 172.20.20.24
...